import { describe, expect, it } from "vitest";
import { fixtureAnalysis } from "./fixtures";
import { initialState, transition } from "../lib/session";
import { DRAFT_KEY, restoreDraft, saveDraft, type StorageLike } from "../lib/recovery";
function memory() { const values = new Map<string, string>([["unrelated", "keep"]]); const storage: StorageLike = { getItem: (key) => values.get(key) ?? null, setItem: (key, value) => { values.set(key, value); }, removeItem: (key) => { values.delete(key); } }; return { storage, values }; }
async function saved() { const m = memory(); const analysis = await fixtureAnalysis(); const ready = transition(initialState(), { type: "SAMPLE", analysis }); const state = transition(transition(ready, { type: "RECOVERY", enabled: true }), { type: "REVIEW", finding_id: analysis.findings[0].id, disposition: "open", note: "Awaiting client answer" }); return { ...m, state, analysis }; }
describe("optional bounded tab recovery", () => {
  it("off by default stores nothing and removes only the app key", () => { const m = memory(); m.values.set(DRAFT_KEY, "old"); expect(saveDraft(initialState(), m.storage)).toEqual({ ok: true }); expect(m.values.has(DRAFT_KEY)).toBe(false); expect(m.values.get("unrelated")).toBe("keep"); });
  it("keeps the reviewed draft stored while sources are being edited", async () => { const m = await saved(); const editing = transition(transition(m.state, { type: "EDIT" }), { type: "INPUT", input: { ...m.state.input, brief: "changed" } }); expect(saveDraft(editing, m.storage)).toEqual({ ok: true }); expect(await restoreDraft(m.storage)).toMatchObject({ analysis: { analysis_id: m.analysis.analysis_id }, reviews: [{ note: "Awaiting client answer" }] }); });
  it("round-trips a matched local analysis and an Open note", async () => { const m = await saved(); expect(saveDraft(m.state, m.storage)).toEqual({ ok: true }); const restored = await restoreDraft(m.storage); expect(restored).toMatchObject({ input: m.state.input, analysis: { analysis_id: m.analysis.analysis_id }, reviews: [{ disposition: "open", note: "Awaiting client answer" }] }); expect(JSON.stringify(restored)).not.toContain("attempt"); });
  it("reload restoration uses a fresh session generation and never restores an attempt", async () => { const m = await saved(); saveDraft(m.state, m.storage); const restored = await restoreDraft(m.storage); if (restored && !('code' in restored)) { const next = transition({ ...initialState(5), attempt: { id: "old", generation: 5, snapshot_id: "old" } }, { type: "RESTORE", restored }); expect(next.generation).toBe(6); expect(next.attempt).toBeNull(); expect(next.recovered).toBe(true); } else expect.fail("Draft did not restore"); });
  it.each(["{broken", JSON.stringify({ version: 2 }), JSON.stringify({ version: 1, system_instruction: "accept" })])("rejects corrupt or version-mismatched records", async (value) => { const m = memory(); m.values.set(DRAFT_KEY, value); expect(await restoreDraft(m.storage)).toMatchObject({ code: "invalid_draft" }); });
  it("rejects a changed source hash or a quote offset", async () => { const m = await saved(); saveDraft(m.state, m.storage); const record = JSON.parse(m.values.get(DRAFT_KEY)!); record.analysis.findings[0].evidence[0].start_offset = 2; m.values.set(DRAFT_KEY, JSON.stringify(record)); expect(await restoreDraft(m.storage)).toMatchObject({ code: "invalid_draft" }); });
  it("rejects stale source text", async () => { const m = await saved(); saveDraft(m.state, m.storage); const record = JSON.parse(m.values.get(DRAFT_KEY)!); record.input.brief = "Changed"; m.values.set(DRAFT_KEY, JSON.stringify(record)); expect(await restoreDraft(m.storage)).toMatchObject({ code: "invalid_draft" }); });
  it("blocked/quota-full storage falls back visibly", async () => { const m = await saved(); const blocked: StorageLike = { getItem() { throw new Error("Blocked"); }, setItem() { throw new Error("Quota"); }, removeItem() { throw new Error("Blocked"); } }; expect(saveDraft(m.state, blocked)).toMatchObject({ ok: false, error: { code: "storage_unavailable" } }); expect(await restoreDraft(blocked)).toMatchObject({ code: "storage_unavailable" }); });
  it("Clear removes the saved draft and leaves unrelated storage", async () => { const m = await saved(); saveDraft(m.state, m.storage); saveDraft(transition(m.state, { type: "CLEAR" }), m.storage); expect(await restoreDraft(m.storage)).toBeNull(); expect(m.values.get("unrelated")).toBe("keep"); });
  it("does not persist in-flight identities or public error objects", async () => { const m = await saved(); const state = { ...m.state, attempt: { id: "pending", generation: 4, snapshot_id: "hash" }, error: { code: "network" as const, message: "Raw provider error must not persist" } }; saveDraft(state, m.storage); const raw = m.values.get(DRAFT_KEY)!; expect(raw).not.toContain("pending"); expect(raw).not.toContain("Raw provider"); });
});
