import { describe, expect, it } from "vitest";
import { fixtureAnalysis } from "./fixtures";
import { initialState, transition, type Attempt, type SessionState } from "../lib/session";
const input = { project_title: "Test", brief: "Booking required.", scope: "Email signup." };
async function ready() { const analysis = await fixtureAnalysis(); const s = transition(initialState(), { type: "SAMPLE", analysis }); return { s, analysis }; }
function start(s: SessionState, snapshot_id: string, id = "A") { const attempt: Attempt = { id, generation: s.generation, snapshot_id }; return { s: transition(s, { type: "START", attempt }), attempt }; }
describe("session identities and local review", () => {
  it("a valid result initializes all findings Open", async () => { const analysis = await fixtureAnalysis(); const pending = start(transition(initialState(), { type: "INPUT", input }), analysis.snapshot_id); const s = transition(pending.s, { type: "RESULT", attempt: pending.attempt, analysis }); expect(s.phase).toBe("review"); expect(s.reviews).toEqual([{ finding_id: analysis.findings[0].id, disposition: "open", note: "" }]); });
  it("ignores duplicate starts during a pending attempt", () => { const a = start(initialState(), "hash"); expect(transition(a.s, { type: "START", attempt: { ...a.attempt, id: "B" } })).toBe(a.s); });
  it("edit → B → late A accepts only B even with identical text", async () => { const analysis = await fixtureAnalysis(); const a = start(transition(initialState(), { type: "INPUT", input }), analysis.snapshot_id); const edited = transition(a.s, { type: "INPUT", input }); const b = start(edited, analysis.snapshot_id, "B"); expect(transition(b.s, { type: "RESULT", attempt: a.attempt, analysis })).toBe(b.s); expect(transition(b.s, { type: "RESULT", attempt: b.attempt, analysis }).phase).toBe("review"); });
  it("Clear resets recovery and ignores late results", async () => { const analysis = await fixtureAnalysis(); const a = start({ ...initialState(), recoveryOptIn: true }, analysis.snapshot_id); const cleared = transition(a.s, { type: "CLEAR" }); expect(cleared.recoveryOptIn).toBe(false); expect(cleared.input.brief).toBe(""); expect(transition(cleared, { type: "RESULT", attempt: a.attempt, analysis })).toBe(cleared); });
  it("cancel/retry ignores the old attempt", async () => { const analysis = await fixtureAnalysis(); const a = start(initialState(), analysis.snapshot_id); const cancelled = transition(a.s, { type: "CANCEL" }); const b = start(cancelled, analysis.snapshot_id, "B"); expect(transition(b.s, { type: "RESULT", attempt: a.attempt, analysis })).toBe(b.s); });
  it("does not accept a result for a different snapshot", async () => { const analysis = await fixtureAnalysis(); const a = start(initialState(), "other"); expect(transition(a.s, { type: "RESULT", attempt: a.attempt, analysis })).toBe(a.s); });
  it("preserves input after failure", () => { const a = start(transition(initialState(), { type: "INPUT", input }), "hash"); const s = transition(a.s, { type: "ERROR", attempt: a.attempt, error: { code: "timeout", message: "Timeout" } }); expect(s.input).toEqual(input); expect(s.analysis).toBeNull(); expect(s.error?.code).toBe("timeout"); });
  it("editing invalidates output; cancel editing restores the prior immutable review", async () => { const { s, analysis } = await ready(); const edited = transition(transition(s, { type: "EDIT" }), { type: "INPUT", input: { ...input, brief: "changed" } }); expect(edited.analysis).toBeNull(); const restored = transition(edited, { type: "CANCEL_EDIT" }); expect(restored.analysis).toEqual(analysis); expect(restored.input).toEqual(input); });
  it("an awaiting-answer note stays Open", async () => { const { s, analysis } = await ready(); const next = transition(s, { type: "REVIEW", finding_id: analysis.findings[0].id, disposition: "open", note: "Awaiting client date answer" }); expect(next.reviews[0]).toMatchObject({ disposition: "open", note: "Awaiting client date answer" }); expect(next.revision).toBeGreaterThan(s.revision); });
  it.each(["decision_recorded", "dismissed"] as const)("requires a note for %s", async (disposition) => { const { s, analysis } = await ready(); expect(transition(s, { type: "REVIEW", finding_id: analysis.findings[0].id, disposition, note: "  " })).toBe(s); });
  it("Reopen retains the recorded note", async () => { const { s, analysis } = await ready(); const decided = transition(s, { type: "REVIEW", finding_id: analysis.findings[0].id, disposition: "decision_recorded", note: "User reports date agreed" }); const reopened = transition(decided, { type: "REVIEW", finding_id: analysis.findings[0].id, disposition: "open", note: decided.reviews[0].note }); expect(reopened.reviews[0]).toMatchObject({ disposition: "open", note: "User reports date agreed" }); });
  it("bounds saved and draft notes and never changes AI claims", async () => { const { s, analysis } = await ready(); expect(transition(s, { type: "REVIEW", finding_id: analysis.findings[0].id, disposition: "open", note: "x".repeat(601) })).toBe(s); const next = transition(s, { type: "DRAFT", finding_id: analysis.findings[0].id, note: "Changed draft" }); expect(next.analysis).toBe(analysis); expect(next.revision).toBe(s.revision + 1); });
});
