import { test, expect } from "@playwright/test";
import { sampleAnalysis, SAMPLE_INPUT } from "../lib/sample";
import fs from "node:fs/promises";
import { makeSnapshot, validateCandidate } from "../lib/evidence";
import { attachMetadata } from "../lib/analysis";
import { isError } from "../lib/contracts";
import type { Page, Locator } from "@playwright/test";
async function tabTo(page: Page, target: Locator) { for (let i = 0; i < 60; i++) { if (await target.evaluate((element) => element === document.activeElement)) return; await page.keyboard.press("Tab"); } throw new Error("Control was not reachable using Tab"); }
test("empty → example → truthful unavailable provider", async ({ page, request }) => {
  await page.goto("/"); await expect(page.getByRole("button", { name: "Compare documents", exact: true })).toBeDisabled();
  await expect(page.locator(".privacy-copy")).toContainText("Compare sends both documents to an AI service");
  await page.getByRole("button", { name: "Use example texts" }).click(); await page.getByRole("button", { name: "Compare documents", exact: true }).click();
  await expect(page.locator(".error-box[role=alert]")).toContainText("authorized server-side API key"); await expect(page.getByLabel("Client brief", { exact: true })).toHaveValue(SAMPLE_INPUT.brief);
  const invalid = await request.post("/api/analyze", { data: { brief: " ", scope: "x" } }); expect(invalid.status()).toBe(400); expect(invalid.headers()["cache-control"]).toBe("no-store");
  const crossOrigin = await request.post("/api/analyze", { data: SAMPLE_INPUT, headers: { origin: "https://evil.test" } }); expect(crossOrigin.status()).toBe(400);
});
test("sample review → evidence → Open note → recorded decision → frozen report/export", async ({ page }) => {
  let apiCalls = 0; page.on("request", (r) => { if (r.url().endsWith("/api/analyze")) apiCalls++; });
  await page.goto("/"); await page.getByRole("button", { name: "Explore sample review" }).click();
  await expect(page.getByText("Sample data", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "Open filter" })).toHaveText("Open 3");
  await page.getByRole("button", { name: "The launch dates disagree", exact: true }).click(); await page.getByRole("button", { name: "View Client brief, line 2 in source" }).click();
  await expect(page.locator("mark")).toHaveText("Launch on 20 October 2026."); await expect(page.locator("mark")).toBeFocused();
  await page.getByLabel("Your review note").fill("Awaiting client date answer"); await page.getByRole("button", { name: "Save Open note" }).click();
  await page.getByRole("button", { name: "Preview report", exact: true }).click(); await expect(page.getByRole("heading", { name: "Decisions still needed", exact: true })).toBeVisible(); await expect(page.getByText("Awaiting client date answer", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "02 Review" }).click(); await expect(page.getByRole("heading", { name: "The launch dates disagree", exact: true })).toBeVisible(); await page.getByLabel("Your review note").fill("User reports 27 October agreed"); await page.getByRole("button", { name: "Record decision", exact: true }).click();
  await page.getByRole("button", { name: "03 Report" }).click(); await expect(page.getByText("Preview is outdated", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "Download Markdown" })).toBeDisabled();
  await page.getByRole("button", { name: "Refresh preview" }).click(); await expect(page.getByText("User reports 27 October agreed", { exact: true })).toBeVisible();
  const downloadEvent = page.waitForEvent("download"); await page.getByRole("button", { name: "Download Markdown" }).click(); const download = await downloadEvent; expect(download.suggestedFilename()).toBe("briefcheck-report.md"); await fs.mkdir("evidence", { recursive: true }); await download.saveAs("evidence/briefcheck-sample-report.md"); const md = await fs.readFile("evidence/briefcheck-sample-report.md", "utf8"); expect(md).toContain("User reports 27 October agreed"); expect(md).toContain("Included: 3 · Omitted dismissed: 0"); expect(md).toContain("Sample data — illustrative findings written by hand. No AI analysis was run."); expect(apiCalls).toBe(0);
  await page.screenshot({ path: "evidence/report-desktop.png", fullPage: true }); await page.emulateMedia({ media: "print" }); await page.pdf({ path: "evidence/briefcheck-sample-report.pdf", format: "A4", printBackground: true });
});
test("dismiss/reopen, filter, sample replacement and edit cancellation preserve review", async ({ page }) => {
  await page.goto("/"); await page.getByRole("button", { name: "Explore sample review" }).click(); await page.getByRole("button", { name: "Booking form is not in the scope", exact: true }).click(); await page.getByLabel("Your review note").fill("Booking is out of this agreed phase"); await page.getByRole("button", { name: "Dismiss finding" }).click();
  await page.getByRole("button", { name: "Dismissed filter" }).click(); await page.getByRole("button", { name: "Reopen finding" }).click(); await page.getByRole("button", { name: "All findings filter" }).click(); await expect(page.getByLabel("Your review note")).toHaveValue("Booking is out of this agreed phase");
  await page.getByRole("button", { name: "Edit sources" }).click(); await page.getByLabel("Client brief", { exact: true }).fill("Changed"); await page.getByRole("button", { name: "Cancel editing" }).click(); await expect(page.getByLabel("Your review note")).toHaveValue("Booking is out of this agreed phase");
  await page.getByRole("button", { name: "Clear session", exact: true }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await page.getByRole("button", { name: "Keep working" }).click(); await expect(page.getByLabel("Your review note")).toHaveValue("Booking is out of this agreed phase");
});
test("loading, slow state, cancel/retry and invalid evidence preserve inputs", async ({ page }) => {
  const analysis = await sampleAnalysis(); let calls = 0;
  await page.route("**/api/analyze", async (route) => { calls++; if (calls === 1) return; const bad = structuredClone(analysis); bad.findings[0].evidence[0].quote = "Invented quote"; await route.fulfill({ json: { ok: true, analysis: bad } }); });
  await page.goto("/"); await page.getByRole("button", { name: "Use example texts" }).click(); await page.clock.install(); await page.getByRole("button", { name: "Compare documents", exact: true }).click();
  await expect(page.getByText("Comparing your documents…", { exact: true })).toBeVisible(); await expect(page.getByRole("button", { name: "Compare documents", exact: true })).toBeDisabled(); await page.clock.runFor(15_100); await expect(page.getByText("Still working. You can cancel this attempt.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Cancel comparison" }).click(); await expect(page.locator(".error-box[role=alert]")).toContainText("cancelled"); await page.getByRole("button", { name: "Retry comparison" }).click(); await expect(page.locator(".error-box[role=alert]")).toContainText("rejected"); await expect(page.getByLabel("Client brief", { exact: true })).toHaveValue(SAMPLE_INPUT.brief); expect(calls).toBe(2);
});
test("optional recovery restores locally; Clear removes only BriefCheck draft", async ({ page }) => {
  let calls = 0; page.on("request", (r) => { if (r.url().endsWith("/api/analyze")) calls++; }); await page.goto("/");
  await page.getByRole("button", { name: "Explore sample review" }).click(); await page.getByLabel("Your review note").fill("Awaiting client answer"); await page.getByRole("button", { name: "Save Open note" }).click(); await page.getByLabel("Keep this draft in this tab").check(); await page.evaluate(() => sessionStorage.setItem("unrelated", "keep")); await page.reload();
  await expect(page.getByText("Recovered local draft", { exact: true })).toBeVisible(); await expect(page.getByLabel("Your review note")).toHaveValue("Awaiting client answer"); expect(calls).toBe(0);
  await page.getByRole("button", { name: "Clear session", exact: true }).click(); await page.getByRole("button", { name: "Clear this session" }).click(); await expect(page.getByLabel("Keep this draft in this tab")).not.toBeChecked(); await page.reload(); await expect(page.getByLabel("Client brief", { exact: true })).toHaveValue(""); expect(await page.evaluate(() => sessionStorage.getItem("unrelated"))).toBe("keep");
});
test("corrupt and blocked recovery has a visible memory fallback", async ({ page }) => {
  await page.addInitScript(() => { sessionStorage.setItem("briefcheck.draft.v1", "{broken"); }); await page.goto("/"); await expect(page.locator(".error-box[role=alert]")).toContainText("not restored"); await page.getByLabel("Keep this draft in this tab").check();
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new Error("Quota full"); }; }); await page.getByLabel("Client brief", { exact: true }).fill("A brief"); await expect(page.locator(".error-box[role=alert]")).toContainText("could not be saved");
});
test("mobile and keyboard complete the sample workflow without overflow", async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto("/"); await expect(page.getByRole("button", { name: "Clear session", exact: true })).toBeEnabled(); await page.screenshot({ path: "evidence/compare-mobile.png", fullPage: true });
  await tabTo(page, page.getByRole("button", { name: "Explore sample review" })); await page.keyboard.press("Enter"); await expect(page.getByRole("heading", { name: "Honey & Rye · campaign delivery plan", level: 1 })).toBeVisible();
  await tabTo(page, page.getByRole("button", { name: "The launch dates disagree", exact: true })); await page.keyboard.press("Enter"); await tabTo(page, page.getByRole("button", { name: "View Delivery plan, line 2 in source" })); await page.keyboard.press("Enter"); await expect(page.locator("mark")).toHaveText("Launch on 27 October 2026.");
  await page.screenshot({ path: "evidence/review-mobile.png", fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await tabTo(page, page.getByRole("button", { name: "Preview report", exact: true })); await page.keyboard.press("Enter"); await expect(page.getByRole("button", { name: "Download Markdown" })).toBeEnabled(); await page.screenshot({ path: "evidence/report-mobile.png", fullPage: true }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
  await tabTo(page, page.getByRole("button", { name: "Download Markdown" })); const download = page.waitForEvent("download"); await page.keyboard.press("Enter"); expect((await download).suggestedFilename()).toBe("briefcheck-report.md");
});
test("neutral abstention, zero findings and limited results preserve their limits", async ({ page }) => {
  const analysis = await sampleAnalysis(); analysis.status = "not_comparable"; analysis.findings = []; analysis.comparison_evidence = ["brief", "scope"].map((id) => { const source = analysis.sources[id as "brief" | "scope"]; const line = source.lines[0]; return { source_id: source.id, start_line: 1, end_line: 1, quote: source.text.slice(0, line.end), start_offset: 0, end_offset: line.end, source_hash: source.sha256, label: `${id === "brief" ? "Client brief" : "Delivery plan"}, line 1` }; });
  await page.route("**/api/analyze", (route) => route.fulfill({ json: { ok: true, analysis } })); await page.goto("/"); await page.getByRole("button", { name: "Use example texts" }).click(); await page.getByRole("button", { name: "Compare documents", exact: true }).click(); await expect(page.getByRole("heading", { name: "These texts do not provide a comparable brief and scope." })).toBeVisible(); await expect(page.getByRole("button", { name: "Preview report", exact: true })).toBeDisabled();
  // This is a synthetic status fixture; model appropriateness is judged in E08/E11 live evaluation.
  await page.unroute("**/api/analyze"); analysis.status = "complete"; analysis.comparison_evidence = []; await page.route("**/api/analyze", (route) => route.fulfill({ json: { ok: true, analysis } })); await page.getByRole("button", { name: "Return to editing" }).click(); await page.getByRole("button", { name: "Compare documents", exact: true }).click(); await expect(page.getByRole("heading", { name: "No issues identified in these texts." })).toBeVisible(); await expect(page.getByText("This does not certify a complete scope.", { exact: true })).toBeVisible();
  await page.unroute("**/api/analyze"); const limited = await sampleAnalysis(); limited.status = "limited"; await page.route("**/api/analyze", (route) => route.fulfill({ json: { ok: true, analysis: limited } })); await page.getByRole("button", { name: "Edit sources" }).click(); await page.getByRole("button", { name: "Compare documents", exact: true }).click(); await expect(page.getByText("Additional issues may exist — limited analysis.", { exact: true })).toBeVisible(); await page.getByRole("button", { name: "Preview report", exact: true }).click(); await expect(page.locator(".report-document")).toContainText("Additional issues may exist");
});
test("embedded scripts/links stay inert; failed copy keeps the report", async ({ page }) => {
  const brief = 'Booking required.\n<script>window.pwned=true</script>\n![remote](https://evil.test/image)'; const scope = "Email signup."; const sources = await makeSnapshot({ brief, scope }); const candidate = validateCandidate({ schema_version: 1, status: "complete", comparison_evidence: [], findings: [{ kind: "missing_from_scope", title: "Booking gap", rationale: "Booking is not named in scope.", question: "Include booking?", scope_assessment: { assessment: "not_found", basis: "Scope lists only signup." }, evidence: [{ source_id: "brief", start_line: 1, end_line: 3, quote: brief }] }] }, sources); if (isError(candidate)) throw new Error("Invalid browser fixture"); const analysis = attachMetadata(candidate, sources, { origin: "sample", duration_ms: 0 }); let unwanted = 0; page.on("request", (r) => { if (r.url().includes("evil.test")) unwanted++; });
  await page.route("**/api/analyze", (route) => route.fulfill({ json: { ok: true, analysis } })); await page.goto("/"); await page.getByLabel("Client brief", { exact: true }).fill(brief); await page.getByLabel("Proposed delivery plan", { exact: true }).fill(scope); await page.getByRole("button", { name: "Compare documents", exact: true }).click(); await expect(page.getByText("<script>window.pwned=true</script>", { exact: false }).first()).toBeVisible(); await page.getByLabel("Your review note").fill('<img src="https://evil.test/note" onerror="window.pwned=true">'); await page.getByRole("button", { name: "Save Open note" }).click(); await page.getByRole("button", { name: "Preview report", exact: true }).click();
  await page.evaluate(() => { Object.defineProperty(navigator, "clipboard", { value: { writeText: () => Promise.reject(new Error("Blocked")) }, configurable: true }); }); await page.getByRole("button", { name: "Copy Markdown" }).click(); await expect(page.getByRole("status")).toContainText("Copy failed"); await expect(page.getByRole("button", { name: "Download Markdown" })).toBeEnabled(); expect(unwanted).toBe(0); expect(await page.evaluate(() => "pwned" in window)).toBe(false); await expect(page.locator("main img,main script,main iframe")).toHaveCount(0);
});
test("60-second UI timeout and Clear while pending do not restore a draft", async ({ page }) => {
  await page.route("**/api/analyze", () => {}); await page.goto("/"); await page.getByRole("button", { name: "Use example texts" }).click(); await page.clock.install(); await page.getByRole("button", { name: "Compare documents", exact: true }).click(); await expect(page.getByText("Comparing your documents…", { exact: true })).toBeVisible(); await page.clock.runFor(60_100); await expect(page.locator(".error-box[role=alert]")).toContainText("timed out"); await page.getByRole("button", { name: "Retry comparison" }).click(); await page.getByLabel("Keep this draft in this tab").check(); await page.getByRole("button", { name: "Clear session", exact: true }).click(); await page.getByRole("button", { name: "Clear this session" }).click(); await expect(page.getByLabel("Client brief", { exact: true })).toHaveValue(""); expect(await page.evaluate(() => sessionStorage.getItem("briefcheck.draft.v1"))).toBeNull();
});
test("desktop/medium layouts and sample replacement are reviewable", async ({ page }) => {
  await page.goto("/"); await expect(page.getByRole("button", { name: "Clear session", exact: true })).toBeEnabled(); await page.screenshot({ path: "evidence/compare-desktop.png", fullPage: true }); await page.getByRole("button", { name: "Use example texts" }).click(); await page.getByRole("button", { name: "Explore sample review" }).click(); await expect(page.getByRole("dialog")).toBeVisible(); await page.getByRole("button", { name: "Replace and continue" }).click(); await page.getByRole("button", { name: "The launch dates disagree", exact: true }).click(); await page.getByRole("button", { name: "View Client brief, line 2 in source" }).click(); await page.screenshot({ path: "evidence/review-desktop.png", fullPage: true }); await page.setViewportSize({ width: 900, height: 900 }); expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true); await expect(page.getByLabel("Your review note")).toBeVisible(); await page.screenshot({ path: "evidence/review-medium.png", fullPage: true });
});
for (const [code, message] of [["rate_limit", "AI service is busy"], ["capacity", "too long to analyse"], ["refused", "declined to complete"], ["invalid_response", "valid result"], ["network", "could not be reached"]]) {
  test(`safe ${code} error preserves documents and requires manual retry`, async ({ page }) => {
    let requests = 0;
    await page.route("**/api/analyze", async route => { requests++; await route.fulfill({ status: code === "rate_limit" ? 429 : 502, json: { ok: false, error: { code, message: "PRIVATE_PROVIDER_DETAIL" } } }); });
    await page.goto("/"); await page.getByRole("button", { name: "Use example texts" }).click(); await page.getByRole("button", { name: "Compare documents", exact: true }).click();
    await expect(page.locator(".error-box[role=alert]")).toContainText(message); await expect(page.locator("body")).not.toContainText("PRIVATE_PROVIDER_DETAIL");
    await expect(page.getByLabel("Client brief", { exact: true })).toHaveValue(SAMPLE_INPUT.brief); await expect(page.getByLabel("Proposed delivery plan", { exact: true })).toHaveValue(SAMPLE_INPUT.scope);
    expect(requests).toBe(1); await expect(page.getByRole("button", { name: "Retry comparison" })).toBeEnabled();
  });
}

test("uploaded documents fill a source, rejected files leave it unchanged, and undo restores typed text", async ({ page }) => {
  await page.goto("/"); await page.locator("#scope").fill("My own plan");
  await page.getByLabel("Upload a file for Client brief").setInputFiles({ name: "brief.txt", mimeType: "text/plain", buffer: Buffer.from("Booking form required.\r\nLaunch on 20 October.\r\n") });
  await expect(page.locator("#brief")).toHaveValue("Booking form required.\nLaunch on 20 October.");
  await page.getByLabel("Upload a file for Proposed delivery plan").setInputFiles({ name: "fake.pdf", mimeType: "application/pdf", buffer: Buffer.from("not a pdf") });
  await expect(page.locator(".input-limit-error")).toContainText("fake.pdf was rejected"); await expect(page.locator("#scope")).toHaveValue("My own plan");
  await page.getByLabel("Upload a file for Proposed delivery plan").setInputFiles({ name: "plan.md", mimeType: "text/markdown", buffer: Buffer.from("Email signup.") });
  await expect(page.locator("#scope")).toHaveValue("Email signup."); await page.getByRole("button", { name: "Undo" }).click(); await expect(page.locator("#scope")).toHaveValue("My own plan");
});
