import { useState } from "react";
import type { Disposition } from "../lib/contracts";
import { toMarkdown, type ReportDocument } from "../lib/report";
import { KIND_LABEL, OriginBadge } from "./Review";
export function Report({ report, outdated, unsaved, onRefresh }: { report: ReportDocument; outdated: boolean; unsaved: boolean; onRefresh: (includeDismissed: boolean) => void }) {
  const [message, setMessage] = useState(""); const a = report.analysis;
  async function copy() { try { await navigator.clipboard.writeText(toMarkdown(report)); setMessage("Markdown copied."); } catch { setMessage("Copy failed. Your preview and notes are preserved; try Download Markdown or Print / Save as PDF."); } }
  function download() { try { const url = URL.createObjectURL(new Blob([toMarkdown(report)], { type: "text/markdown;charset=utf-8" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = "briefcheck-report.md"; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000); setMessage("Markdown download requested."); } catch { setMessage("Download failed. Your preview and notes are preserved; try Copy Markdown or Print / Save as PDF."); } }
  const disabled = outdated || unsaved;
  const sections: { disposition: Disposition; title: string }[] = [{ disposition: "open", title: "Decisions still needed" }, { disposition: "decision_recorded", title: "Decisions recorded" }, ...(report.options.include_dismissed ? [{ disposition: "dismissed" as const, title: "Dismissed findings" }] : [])];
  return <>
    <section className="workspace-heading no-print"><div><p className="eyebrow">Report</p><h1>Report preview</h1><p className="lede">This is exactly what will be exported. Exports are created in your browser; nothing is sent.</p><OriginBadge origin={a.origin} /></div></section>
    <div className="report-controls no-print"><label className="checkbox-label"><input type="checkbox" checked={report.options.include_dismissed} disabled={unsaved} onChange={(e) => onRefresh(e.target.checked)} />Include dismissed findings</label><div className="button-row wrap"><button disabled={disabled} onClick={copy}>Copy Markdown</button><button disabled={disabled} onClick={() => { window.print(); }}>Print / Save as PDF</button><button className="primary" disabled={disabled} onClick={download}>Download Markdown</button></div></div>
    {(outdated || unsaved) && <div className="warning no-print"><div><strong>{outdated ? "Preview is outdated" : "Unsaved note"}</strong><p>{outdated ? "The review changed. Refresh before exporting." : "Save your note on the Review screen before exporting."}{outdated && unsaved && " Save your note first."}</p></div><button disabled={unsaved} onClick={() => onRefresh(report.options.include_dismissed)}>Refresh preview</button></div>}{message && <p role="status" className="export-message no-print">{message}</p>}
    {disabled && <section className="print-blocker"><h2>Report not printed</h2><p>{unsaved ? "Save your notes and refresh the preview before printing." : "Refresh the preview before printing."}</p><p>The frozen preview no longer represents the current review. No report content is printed.</p></section>}
    <article className={`report-document${disabled ? " report-print-blocked" : ""}`}><header className="report-title"><p className="eyebrow">BriefCheck / Decision report</p><h2>{a.sources.project_title || "Untitled comparison"}</h2><p className={`report-state${report.draft ? " draft" : ""}`}>{report.draft ? "Draft · Open decisions remain" : "Review recorded · Scope completeness is not certified"}</p><p>Original documents are unchanged. Recorded outcomes are user-reported; client assent is unverified.</p>{a.origin === "sample" && <p className="report-origin">Sample data — illustrative findings written by hand. No AI analysis was run.</p>}{a.status === "limited" && <p className="warning">Additional issues may exist — limited analysis.</p>}<dl className="report-stats">{([["Open", report.counts.open], ["Decision recorded", report.counts.decision_recorded], ["Dismissed", report.counts.dismissed]] as const).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="report-counts">{report.counts.all} findings in total · {report.counts.included} included in this report · {report.counts.omitted} dismissed omitted</p></header>
    {sections.map((section) => <section className="report-section" key={section.disposition}><h2>{section.title}</h2>{!report.reviews.some((r) => r.disposition === section.disposition) && <p className="muted">{section.disposition === "open" ? "No open questions. This does not certify a complete scope." : "None recorded yet."}</p>}{report.reviews.filter((r) => r.disposition === section.disposition).map((r) => { const f = a.findings.find((f) => f.id === r.finding_id)!; return <div className="report-item" key={f.id}><p className="eyebrow">{KIND_LABEL[f.kind]} · {section.disposition.replaceAll("_", " ")}</p><h3>{f.title}</h3><p className="report-question">{f.question}</p><h3 className="report-subhead">Potential business consequence</h3><p>{f.rationale}</p>{f.scope_assessment && <p className="absence-note"><strong>Full-scope absence assessment:</strong> {f.scope_assessment.basis} <span className="muted">Interpretation, not proof of absence.</span></p>}{f.evidence.map((e, i) => <blockquote key={i}><span className="citation">{e.label} · Quote matched</span><p>{e.quote}</p></blockquote>)}<div className="report-note"><strong>User note{r.disposition === "decision_recorded" ? " / recorded outcome" : ""}</strong><p>{r.note || "None recorded."}</p></div></div>; })}</section>)}
    </article>
  </>;
}
