import { useEffect, useState } from "react";
import type { Disposition, EvidenceSpan, FindingKind, ValidatedAnalysis } from "../lib/contracts";
import { hasUnsavedNotes, type SessionEvent, type SessionState } from "../lib/session";
import { SourceViewer } from "./SourceViewer";
export const KIND_LABEL: Record<FindingKind, string> = { missing_from_scope: "Missing from scope", conflict: "Conflict", clarification: "Clarification" };
const KIND_ORDER: FindingKind[] = ["missing_from_scope", "conflict", "clarification"];
const STATE_LABEL: Record<Disposition, string> = { open: "Open", decision_recorded: "Decision recorded", dismissed: "Dismissed" };
export function OriginBadge({ origin }: { origin: ValidatedAnalysis["origin"] }) {
  return origin === "sample"
    ? <p className="origin-badge sample"><strong>Sample data</strong><span>Illustrative findings written by hand. No AI analysis was run.</span></p>
    : <p className="origin-badge"><strong>AI-assisted</strong><span>Quotes are verified against your documents. Interpretations need your review.</span></p>;
}
export function Review({ state, dispatch, onEdit, onReport, selected, onSelect }: { state: SessionState; dispatch: (event: SessionEvent) => void; onEdit: () => void; onReport: () => void; selected: string; onSelect: (id: string) => void }) {
  const analysis = state.analysis!; const [filter, setFilter] = useState<Disposition | "all">("all"); const [evidence, setEvidence] = useState<EvidenceSpan | null>(null);
  // Display order (grouped by kind), so "first" means the first card on screen.
  const visible = analysis.findings.filter((f) => filter === "all" || state.reviews.find((r) => r.finding_id === f.id)?.disposition === filter).sort((a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind));
  const unsaved = analysis.findings.filter((f) => state.drafts[f.id] !== undefined && state.drafts[f.id] !== state.reviews.find((r) => r.finding_id === f.id)?.note);
  useEffect(() => { if (!visible.some((f) => f.id === selected)) { onSelect(visible[0]?.id ?? ""); setEvidence(null); } }, [visible, selected, onSelect]);
  // Fall back to the first visible finding so the first render never flashes an empty panel.
  const finding = visible.find((f) => f.id === selected) ?? visible[0]; const review = finding && state.reviews.find((r) => r.finding_id === finding.id); const note = finding ? state.drafts[finding.id] ?? review?.note ?? "" : "";
  const counts = Object.fromEntries((["open", "decision_recorded", "dismissed"] as const).map((d) => [d, state.reviews.filter((r) => r.disposition === d).length]));
  return <>
    <section className="workspace-heading"><div><p className="eyebrow">Review</p><h1>{analysis.sources.project_title || "Untitled comparison"}</h1><p className="heading-meta"><span>{analysis.findings.length} {analysis.findings.length === 1 ? "finding" : "findings"}</span><span>{counts.open} open</span><span>{counts.decision_recorded} decided</span><span>{counts.dismissed} dismissed</span></p><OriginBadge origin={analysis.origin} /></div><div className="button-row"><button onClick={onEdit}>Edit sources</button><button className="primary" onClick={onReport} disabled={analysis.status === "not_comparable" || hasUnsavedNotes(state)} aria-describedby={unsaved.length ? "unsaved-notes" : undefined}>Preview report <span aria-hidden="true">→</span></button></div></section>
    {unsaved.length > 0 && <div className="warning" id="unsaved-notes" role="status"><span>{unsaved.length === 1 ? "1 finding has an unsaved note. Save it" : `${unsaved.length} findings have unsaved notes. Save them`} before previewing the report.</span>{unsaved[0].id !== finding?.id && <button onClick={() => { setFilter("all"); onSelect(unsaved[0].id); setEvidence(null); }}>Go to “{unsaved[0].title}”</button>}</div>}
    {analysis.status === "limited" && <div className="warning">Additional issues may exist — limited analysis.</div>}
    {analysis.status === "not_comparable" ? <section className="empty-state"><h2>These texts do not provide a comparable brief and scope.</h2>{analysis.comparison_evidence.map((e, i) => <blockquote key={i}><span className="citation">{e.label} · Quote matched</span><p>{e.quote}</p></blockquote>)}<button onClick={onEdit}>Return to editing</button></section> : <>
    <div className="review-toolbar"><div className="filters">{(["all", "open", "decision_recorded", "dismissed"] as const).map((d) => <button key={d} aria-label={d === "all" ? "All findings filter" : `${STATE_LABEL[d]} filter`} aria-pressed={filter === d} onClick={() => setFilter(d)}>{d === "all" ? `All ${analysis.findings.length}` : `${STATE_LABEL[d]} ${counts[d]}`}</button>)}</div></div>
    {!analysis.findings.length ? <section className="empty-state"><h2>No issues identified in these texts.</h2><p>This does not certify a complete scope.</p></section> : <div className="review-grid"><nav className="finding-list" aria-label="Findings">{KIND_ORDER.map((kind) => <div key={kind}>{visible.some((f) => f.kind === kind) && <h2 className="group-heading"><span className={`kind-dot ${kind}`} aria-hidden="true" />{KIND_LABEL[kind]} <span className="group-count">{visible.filter((f) => f.kind === kind).length}</span></h2>}{visible.filter((f) => f.kind === kind).map((f) => <button key={f.id} className={`finding-card ${f.id === finding?.id ? "selected" : ""}`} aria-label={f.title} aria-pressed={f.id === finding?.id} onClick={() => { onSelect(f.id); setEvidence(null); }}><strong>{f.title}</strong>{(() => { const d = state.reviews.find((r) => r.finding_id === f.id)!.disposition; return <span className={`status-pill ${d}`}>{STATE_LABEL[d]}</span>; })()}</button>)}</div>)}</nav>
    {finding && review ? <section className="finding-detail" key={finding.id}><span className={`kind-tag ${finding.kind}`}>{KIND_LABEL[finding.kind]}</span><h2>{finding.title}</h2><h3>Potential business consequence</h3><p className="rationale">{finding.rationale}</p><div className="question-box"><span className="eyebrow">Clarification to settle</span><p>{finding.question}</p></div><h3>Source evidence</h3>{finding.evidence.map((e, i) => <blockquote key={i}><div className="quote-top"><button className="citation" aria-label={`View ${e.label} in source`} onClick={() => setEvidence({ ...e })}>{e.label} <span aria-hidden="true">↗</span></button><span className="matched">Quote matched</span></div><p>{e.quote}</p></blockquote>)}{finding.scope_assessment && <div className="absence-note"><strong>Full-scope absence assessment</strong><p>{finding.scope_assessment.basis}</p><span className="muted">{analysis.origin === "sample" ? "Sample judgement" : "AI judgement"}, not a quote · check the full delivery plan in Source documents.</span></div>}
    <div className="notes-section"><div className="quote-top"><label htmlFor="review-note">Your review note</label><span className="muted note-count">{note.length} / 600</span></div><textarea id="review-note" value={note} maxLength={600} onChange={(e) => dispatch({ type: "DRAFT", finding_id: finding.id, note: e.target.value })} placeholder="Keep a question open, record an outcome, or explain a dismissal…" /><p className="note-hint">State: <span className={`status-pill ${review.disposition}`}>{STATE_LABEL[review.disposition]}</span> A note is required to record a decision or dismiss. Notes never change the source documents.</p><div className="button-row wrap note-actions"><button className="primary" disabled={!note.trim()} onClick={() => dispatch({ type: "REVIEW", finding_id: finding.id, disposition: "decision_recorded", note })}>Record decision</button><button onClick={() => dispatch({ type: "REVIEW", finding_id: finding.id, disposition: "open", note })}>Save Open note</button><button className="text-button danger" disabled={!note.trim()} onClick={() => dispatch({ type: "REVIEW", finding_id: finding.id, disposition: "dismissed", note })}>Dismiss finding</button>{review.disposition !== "open" && <button onClick={() => { setFilter("all"); dispatch({ type: "REVIEW", finding_id: finding.id, disposition: "open", note }); }}>Reopen finding</button>}</div>{note !== review.note && <p className="unsaved" role="status">Unsaved note — save it before refreshing the report.</p>}</div></section> : <section className="empty-state"><h2>This filter has no findings.</h2><button onClick={() => setFilter("all")}>Show all findings</button></section>}
    <SourceViewer sources={analysis.sources} evidence={evidence} /></div>}</>}
  </>;
}
