import { attachMetadata } from "./analysis.ts";
import { isError, type ValidatedAnalysis } from "./contracts.ts";
import { makeSnapshot, validateCandidate } from "./evidence.ts";
export const SAMPLE_INPUT = { project_title: "Honey & Rye · campaign delivery plan", brief: "Build a five-page bakery website with a booking form and an email signup.\nLaunch on 20 October 2026.\nThe site must be fast on mobile.\nLaunch supports the bakery's 20 October campaign; booking must be available on launch day.", scope: "Deliver a five-page bakery website and an email signup.\nLaunch on 27 October 2026.\nInclude responsive layouts; performance targets are not defined." };
export async function sampleAnalysis(): Promise<ValidatedAnalysis> {
  const sources = await makeSnapshot(SAMPLE_INPUT);
  const resolved = validateCandidate({ schema_version: 1, status: "complete", comparison_evidence: [], findings: [
    { kind: "conflict", title: "The launch dates disagree", rationale: "The brief asks for 20 October; the delivery plan commits to 27 October. The later launch may miss the stated 20 October campaign. Delivery feasibility and any commercial effect remain unverified.", question: "Can the team commit to the required 20 October launch, including booking, or should the client move the campaign to 27 October?", evidence: [{ source_id: "brief", start_line: 2, end_line: 2, quote: "Launch on 20 October 2026." }, { source_id: "scope", start_line: 2, end_line: 2, quote: "Launch on 27 October 2026." }, { source_id: "brief", start_line: 4, end_line: 4, quote: "Launch supports the bakery's 20 October campaign; booking must be available on launch day." }] },
    { kind: "missing_from_scope", title: "Booking form is not in the scope", rationale: "The brief requires booking at launch, but the delivery plan names no booking commitment. The campaign launch may lack the requested booking capability unless the delivery plan or agreed phase changes.", question: "Should booking be added to the launch deliverables, or will the client explicitly accept a later booking phase?", scope_assessment: { assessment: "not_found", basis: "Reading all three delivery-plan lines, no booking form or equivalent deliverable is named." }, evidence: [{ source_id: "brief", start_line: 1, end_line: 1, quote: "Build a five-page bakery website with a booking form and an email signup." }, { source_id: "brief", start_line: 4, end_line: 4, quote: "Launch supports the bakery's 20 October campaign; booking must be available on launch day." }] },
    { kind: "clarification", title: "Mobile performance needs a target", rationale: "“Fast on mobile” has no measurable acceptance criterion, and the delivery plan leaves targets undefined. The client and team may disagree about acceptance and need further work; its extent is unknown.", question: "What mobile performance criterion and test conditions will count as acceptance before delivery is signed off?", evidence: [{ source_id: "brief", start_line: 3, end_line: 3, quote: "The site must be fast on mobile." }, { source_id: "scope", start_line: 3, end_line: 3, quote: "Include responsive layouts; performance targets are not defined." }] },
  ] }, sources);
  if (isError(resolved)) throw new Error("The synthetic sample could not be validated.");
  return attachMetadata(resolved, sources, { origin: "sample", duration_ms: 0 });
}
